---
title: "About me"
---

## Education

My educational background is in the Biological Sciences, I obtained a B.Sc. and M.Sc. from the [university of Konstanz](https://www.uni-konstanz.de/en/). My M.Sc. was focused on Biochemistry, Genetics, and Toxicology. For an internship, I spent half a year in Cape Town at the [IDM](http://www.idm.uct.ac.za/), short for Institute of Infectios Disease and Molecular Medicine, initiating a model to simulate part of the adaptive immune system using *Python*. To complete my studies, I went to Basel and worked at [NBE-Therapeutics](https://www.nbe-therapeutics.com/). Here, my master's thesis was about investigating a coupling strategy for so called [ADCs](https://en.wikipedia.org/wiki/Antibody-drug_conjugate), designed drugs for targeted cancer therapy. Now, I am a doctoral student enrolled at [LMU](https://www.uni-muenchen.de/index.html) and working at the [university hospital](https://www.lmu-klinikum.de/) in Munich. My research focuses on signaling pathways and cellular programs in cancer. 

## Research Philosophy

I am (becoming) a scientist interested in cancer evolution and potential attackpoints for therapy. For my future, I do see myself in the health sector as a data analyst. Open science and *R* are my passion. From my point of view, great amounts of data are just waiting to be analysed to everyone's benefit.

## Selected Publications

1. Schinke, H. and Heider, T. *et al*., Digital scoring of EpCAM and Slug expression as prognostic markers in head and neck squamous cell carcinomas. [*Molecular Oncology*](https://doi.org/10.1002/1878-0261.12886), 2020

2. Schinke, H. *et al.*, Partial epithelial-to-mesenchymal transition is prognostic and associates with Slug in head and neck cancer. **Under review:** *Molecular Oncology*, 2020, Pre-print available: [*bioRxiv*](https://www.biorxiv.org/content/10.1101/2020.10.20.346692v1), 2020

3. Pan, M. and Schinke, H. *et al.*, EpCAM ectodomain EpEX is a ligand of EGFR that
counteracts EGF-mediated epithelial-mesenchymal transition through modulation of
phospho-ERK1/2 in head and neck cancers. [*PLoS Biology*](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2006624), 2018